### ISSUE TITLE
Improving README

### ISSUE THREAD

**Issue by mechtaev** [modus-continens/openjdk-images-case-study#4]
@thevirtuoso1973, could you please also addess some issues with README?

> This repository hosts Modusfile(s) intended to generate OpenJDK images.

Can you please start with a short problem description/motivation and how we address the problem?

> Below is a list that shows the ways in which our OpenJDK

This (in a shorter form) can be a part of motivation. Also, add a link to the original approach and explain why it is bad.

> images in under 15 minutes on a single machine

It is not clear if it is good or bad without comparing with a baseline. Does it take longer with the original scripts?

**Comment by thevirtuoso1973** [comment]
- [x] Right justify numbers
- [x] Rewrite intro/explanation paragraphs
